msFilterList
: Expires=3
#-------【广告强效过滤规则 for ABP】-------
#----一个通用、全面的广告过滤规则----
#----------版本_5.1.0---------
#-----最后更新：2012-04-29------
#-------------广告联盟-------------
- *.0252.com/
-d i.uu06.com
- *.topfriv.com/popup.js
- *.securitymattersmag.com/scripts/popup.js
- *.198game.com/
- *.198game.net/
- *.allthelyrics.com/*/popup.js
- *.y2126.com/
-d pub.buzz-time.com.cn
- *.100fenlm.cn/
- *.adszui.com/
-d p.tanx.com /ex?i=mm_17230573_
-d js.3975.com
- *.ooaaoo.com/
- *.1133.cc/
-d union.zhubajie.com
- *.jugao.com/
- *.100tone.com/
-d js.yoyi.tv
-d js.shenduchuanmei.com
- http://show.k184.com:8080
-d code.yy32.com
-d ads.doublemax.net
-d js.7794lm.com
-d img.alimama.cn /cms/images/*.swf
-d s.334700.com
-d code.100Goo.com
- *.chenjingli.com/
-d s.tiaosa.cn
- *.001union.com/
- *.77union.cn/
-d s.svem.cc
-d c.xsu.cc
- *.07171.com/
- *.369456.com/
-d serve.popads.net
- *popadscdn.net/
- *.tuite8.com/
-d js.ylunion.com
-d js.zfjiu.com
- *.17luntan.com/
- *.186ad.com/
- http://synad*.nuffnang.com.cn/
- *.is686.com/
- *.247realmedia.com/
- *.2bj.cc
- *.2bj.cn/
- *.37cs.com/
- *.37dz.com/
- *.45511.com/
- *.53kf.com/kf.php
- *.59163.com/
- *.5k3g.com/
- *.5zon.com/
- *.778669.com/
- *.779.net
- *.7iam.com/
- *.7pk.com/
- *.8le8le.com/
- *.91ivr.com/
- *.565882.com/
- *.91sanguo.cn
- *.6dad.com/
- *allyes.*/ad
- *.9elm.cn/
- *.9v.cn/
- *.9vcpm.cn/
-d code.ze5.com
- *.adbrite.com/
-d t.yigouw.com
- *.adpinion.com/
- *down.jialichuang.com/
- *.ads8.com/
- *.ads99.net
- *.adsky.net
- *.adtology.com/
- *.adultadworld.com/
- *.advertising.com/
- *.aisf.cn/
- *.bobomedia.com/
- *.burstmedia.com/
- *.chinaih.com/
- *.chitika.com/
- *.clickeye*.cn/
- *.cnxad.com/
- *.cnzz.com/api/*.js
- *.counter.dudu.com/
-d u.3393.com
- *.diyad.cn/
- *.dudusms.
- *.egooad.cn/
- *.egooad.com/
- *.ero-advertising.com/
- *.ete.cn/
- *.eteun.cn/
- *.gamediad.com
- *.getiton.com/
- *.gogocdn.com/
- *.hot200.cn/
-d static.mediav.com
-d material.mediav.com
- *.discuz.net/data/attachment/album/*/*/*.gif
- *.1lo0.net/code/
-d d.yoyi.tv
- *.ifocus.cn/
- *.insenz.com/
- *.itsun.com/
-d p.zhanzhang.net
- *.junnew.com/indexad/
- *.kfwan.com/
- *.leomediachina.
- *.lt77.com
- *.lzjl.com/
- *gamebox.962.net/468.jpg
- *.miaozhen.com/
- *.mr66.com/
- *.myiee.com/
- *.na7.cc/
- *.no3.com.cn/
- *.oadz.com/
- *.ok8848.com/
- *.onetad.com/
- *.pee.cn/
- *.pointroll.com/
- *q78.com.cn/
- *.qq494.cn/
- *.rj518.
- *.rmxads.com/
- *.rubiconproject.com/
- *.scupio.com/
- *.seegogo.net
- *.sms888.net
-d www.top1bet.com /imgs/zp*x*.gif
- *.sparkstudios.com/
- *.t2t2.com/
- *.taobd.com/
- *.the5v.com/
- *.tribalfusion.com/
- *.tuigoo.com/
- *.tx8688.com/
- *.tx908.com/
- *.uinicall.com/
- *.vogate.com/
- *.wangmeng.com/
- *.wauee.com/
- *.web7k7k.net
- *.xxxwebtraffic.com/
- *.yebai.net/
- *.yeeka.com/
- *.yigao.com/
- *.yiqiwin.com/
- *.zhcpm.com
-d www.ipinyou.com
- *autosense.bitauto.com
- *b.todayisp.com
- *.dingge.cc/
- http://bd.yidaba.com
-d www.460.com.cn /*/*x*-*.htm
-d adj.yidaba.com
-d www.hoyiad.com /a/
- *hoyiad.com/images/
- *hoyiad.com/show.php?
-d img.007.mx /flash/*x*.swf
- *yunads.com/a/*-*-*/
- *yunads.com/show.php?
- http://bs.serving-sys.com
- http://chat8.live800.com
- http://cn.lianmeng.com
- http://code.52qiangming.com
-d code.comuce.com /bdcode/
- http://cpv.channelray.com
#----十八和谐综合色区----
-d 98.126.54.107 .gif
- http://dhcode.cn3.cn
- http://display.xpresssyndication.com
- *dotmore.cn
- *dw-cn.com.com/
- http://ec.131377.com
- http://file.chanet.com.cn
- http://gg.12354.com
-d h1.untang.com
- http://y.taolai.cn
- http://y.abang.com
- http://vip.qingdaonews.com
- http://web.kehu.cn
- http://sysimages.tq.cn
- *.ugooo.cc/
- *sellcn.com/
-d server.yoyi.com.cn
- http://mmsu.moyu.com
-d u.imop.com
-d float2006.tq.cn
-d code.woairing.cn /mmscode/MusicSingleRing/
- *cc.kx365.com/
-d tj.37wanwan.com /data/load.php?
-d pic.adhai.com
- *.unionsky.cn/
- *.jizzads.com/
- *.adsue.com/
- *wangrong1002.com
-d res.9dzc.com /tcjs/
- *.heroclick.cn/
- *.000wan.com/
- *.doubleclick.net/
- *.84422.com/
- *.84422.com:*/
-d dw.cbsi.com.cn /js/
-d adportal.cbsi.com.cn
-d t.iloveyouxi.com
- *.cpm360.com/
- *.ssrj.net/
-d cpm.union.52xiyou.com
- *.s2d6.com/x/?
- *.game3737.com/
- *.adkongjian.com
- http://cpp.ggyad.com*/
-d img.shenduchuanmei.com /a/
- *.wrating.com/
- *inter-focus.cn/
- *ip686.com
- *ivru.moyu.com
- http://js.62826.com
- http://js.coogao.cn
- http://js1.339.cn
- http://jsa.733.com
- *kanoodle.com
- *lelecpp.com
- *linkpage.cn/
- http://mmm.mm5208.com
- http://monitor.yigao.com
- *myad.cn/
- http://online4.lianmeng.com
-d p.wanliuliang.com
- http://p4p.cnaz.com
- http://p4p.foundermedia.cn
- http://p4p.tom.com
- http://pages.etology.com
- http://pic.adver.com
- http://popunder.adsrevenue.net
-d popunder.paypopup.com /popup.php
-d ppntv.033.com
- http://pv.tom.com
- http://qq1.moyu.com
- *qqmms.net/adlink/
- *questionmarket.com/
- http://resource.communicatte.com
- *smartcreative.cn/
-d sms.wellsms.com
-d teamwork.enorth.com.cn
-d 33.autohome.cn /file/
- *allyesky.cn/js/
-d au.ipart.cn /comp/hooks.php
-d c.91wan.com
-d c.sfilm.com
-d cache.51go.com
-d cache.blogads.com
-d cm.p4p.cn
-d code.158ad.com
-d code.qqgou.com
-d www.xixianad.com
- http://d*.zedo.com/
- *.826060.com/
- *.1o26.com/
-d code.woainame.cn /code/*.js
- *.maxreturn.cn/
-d p.17kuxun.com
-d cpm.yx121.com
-d go.lele.com
-d ipagent.igalive.com /s.aspx?adid=
- *.sponsorads.de/
- *yceml.net/0106/
-d www.yceml.net
- http://js*.339.cn/
- *.admin6.com/a/
-d jump.admin6.com /iclk/
- *.union188.com/
- *.unionbig.com/
- http://w*ww.blu.livefilestore.com/*.gif
- *.union178.com/
- *qq61.com/
-d u1.skype.tom.com
-d js.a3p4.com
- *.91mt.net/data/js/
-d ads.revsci.net
-d ulinkdir.tom.com
-d ulinkjs.tom.com
- http://online*.cnzz.com/img/
-d uimg.unionli.com
-d www.lf-lm.com
- *.innity.net/
- http://jsa*.733.com/
-d resmkt.dipan.com
-d s.vdoing.com
- *skype-soft.cn
-d sms.7988.net
-d stat.uuu9.com /stat/
-d u.520940.cn
-d u.56wan.com
-d u.7town.com
-d u.ferrygame.com
-d u.haom.us
-d u.molidao.com
-d u.molihe.com
-d u.www.duba.net
-d u.x-push.net
-d uid.mdbchina.com
-d uimg.my4399.com
-d un.265.com
-d un.5i.com
-d v.jymtdm.com
-d vip.78.cn
-d urich20.uitv.com
-d p.tanx.com /ex?i=mm_*_*_
-d u.taotaosou.com
-d www.0731s.net
-d www.101860.com
-d www.18dmm.com
-d www.2myad.com
-d www.52xmm.cn
-d www.59.cn /*gg/
- *.59.cn/test/newgg/
-d img.sharele.cn
-d un.sharele.cn
-d code.u.18dx.com
- *.58cpm.com/iclk/
-d www2.vadcast.com
-d new.netgy.com
-d pic.jdunion.com /excelmedia/
-d pic.jdunion.com /mk/
-d pic.jdunion.com /jdbbs/flash/*.swf
- *.tjhggs.com/
- *.6788787.com/
- *.tjq.com/
- *.qiyou.com/
-d 60.191.124.245 /images/*.jpg
-d 60.191.124.196 .jpg
-d 60.191.124.245 /images/sudu5.gif
- *.333wan.com/
-d l.youxitui.net
- *.9vcpp.com/
- *.360kaixin.com/
-d static.csbew.com /k.js
- *.adtech.de/
- *.jomodns.com/
-d img.mmcdn.cn /t/
-d www.91cy.cn
-d www.91tel.com
-d www.99xqw.com
-d www.algj-27dy.cn .html
- *7794.com
-d www.lduhtrp.net
-d www.d9ad.com
-d www.linkiis.cn
-d www.naqigs.cn
-d www.netgy.com
-d www.newwang.com
-d www.okhaobang.com
-d www.spjoy.com
- *housefun.com.tw/
- *qling.com/
-d union.dvbbs.net
-d un.5d6d.com
-d media.fojafrog.com /mm/materials/player/
- *.88210212.com/
- *.8369.info/
- *66-77.com/
- *adpower.cn/
- *.dn888.com:85/
- *.2bj.cn:8899/
- *.dn888.com/
- *5622.cn/
- *woniu666.com/
- *.blogad.com.tw/
-d s.dalu2000.com /sitespread.php?
- *.37see.com/
- *adsue.com/show.php?
- *.alivv.com/
- *.huangjinlian.cn/imagestuangou/
- *.9wee.com/cluclk?
-d idm666.s159.288idc.com
-d js.qizhao.com
- *c.qling.com
- *dgseo8.com/images/
- *.6693.cc/
- *yinjiasm.com/ima/ggtp/
- *.zjbdt.com/
- *.uctrac.com/
- *.ajiang.net/
- *918kf.com/flash/
- *.vitalads.net/
- *8es.cn/code/
- *.spotrails.com/
- *.59ad.net/
-d media.17leyi.com
-d adsresult.joywell.com.cn
- *.bmgad.com/
-d union.yihaodian.com
-d show.altitudedigitalpartners.com
- *.keydot.net/
-d v2.tjj.com /static/
-d jump.codeo.11.mu /iclk/?
- *udmserve.net/udm/
-d content.yieldmanager.edgesuite.net /atoms/
-d v.xi666.com
-d p.9kele.com
-d mm.3992929.com
-d p.gocsgo.com
-d uimg.xiaoangel.com /jsorigin/
- *rd.apmebf.com/
-d js.xsu.cc
-d cs.twcczhu.com
-d cdn.udmserve.net /mid858/
-d view.admaster.com.cn
-d click.admaster.com.cn
-d code.aizhuanlove.cn /loveimages/
-d code.aizhuanlove.cn /code/
- *snyu.com/
- *.picadmedia.com/
-d static.hhzw.5pk.com
- *.keyyou.net/
- *.cpm9v.cn/
- *.heima8.com/
- *.ad-plus.cn/
-d a12.alphagodaddy.com /?
- *axill.com/banners/
- *.afdads.com/
-d view.atdmt.com /ZH1/iview/
- *.17g.net/
- *cnwebmasters.com/disad/userimages/
-d link.155game.com
- *.bloggerads.net/
- *.mengxiang.in/show.php?
-d code.178gg.com
-d v.9vcpp.cn
-d vtechweb.adsame.com /s?
-d www.114la.com /indexa.html
- *.flunion.cn/
-d www.1717388.com /i.js
- *.ubcpm.com/
-d un.22w.com /show.php?
- *.ad18.com.cn/new2010/11z/
- *19dc.com/a/
- *19dc.com/show.php?
-d static.awempire.com /ban/
-d u.adbutler.com.cn /allsites/
-d pic.loliso.com
- *bitian8g.com/gif/
- *p012.com/Image/TaoBaoAd/
-d img.img18.com /img/unimages/ys2012/images/cr/
- http://c*.uk.jf26.com/show.php?
-d vda.uuzu.com
-d c.x007.org
- *.star8.net/
-d business.92wy.com
- *.i-qianming.cn/
- *.51yes.com/
- *.qq937.com/
- *.371gw.com/
- *.116b.com/
-d www.qutaotao.com /images/*0817.jpg
-d t.gameyule.com
- *.naqigs.com/
- *jinpai123.com/paopaoad.gif
- *js*.9wad.com/
-d code.ceyunshi.cn
-d v.cpp9v.cn
-d sixc.r.arpg2.com
-d yxyz.mttmtt.com /yxyz9.html?code=
- http://media.fastclick.net
- *image.j-a-net.jp/
- *.guruonline.com.hk/
